[package]
name = "player"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
rodio = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
librespot = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }
chrono = { workspace = true }
lofty = { workspace = true }
rustfft = "6"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
stream-download = { version = "0.24", default-features = false, features = ["reqwest", "reqwest-rustls", "temp-storage"] }
